//
//  CLDPublishResourcesRequestParams.swift
//
//  Copyright (c) 2016 Cloudinary (http://cloudinary.com)
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
//

import Foundation

/**
 This class represents the different parameters that can be passed when performing a tag request.
 */
@objc open class CLDPublishResourcesRequestParams: CLDRequestParams {
    
    //MARK: Init
    
    public override init() {
        super.init()
//        self.setParam(PublicResourcesParams.accessMode.rawValue, value: "public")
    }
    
    /**
    Initializes a CLDPublishResourcesRequestParams instance.
    - parameter tag:                The tag to publish resources.
    
    - returns:                       A new instance of CLDPublishResourcesRequestParams.
    */
    internal init(tag: String) {
        super.init()
        setParam(PublicResourcesParams.tag.rawValue, value: tag)
    }
    
    /**
     Initializes a CLDPublishResourcesRequestParams instance.
     - parameter publicIds:           The publicIds to publish resources.
     
     - returns:                       A new instance of CLDPublishResourcesRequestParams.
     */
    internal init(publicIds: [String]) {
        super.init()
        setParam(PublicResourcesParams.publicIds.rawValue, value: publicIds)
    }
    
    /**
     Initializes a CLDPublishResourcesRequestParams instance.
     - parameter prefix:                The prefix to publish resources.
     
     - returns:                       A new instance of CLDPublishResourcesRequestParams.
     */
    internal init(prefix: String) {
        super.init()
        setParam(PublicResourcesParams.prefix.rawValue, value: prefix)
    }
    
    /**
     Initializes a CLDPublishResourcesRequestParams instance.
     
     - parameter params:    A dictionary of the request parameters.
     
     - returns:             A new instance of CLDPublishResourcesRequestParams.
     */
    public init(params: [String : AnyObject]) {
        super.init()
        self.params = params
    }
    
    // MARK: - Get Params
    
    open var publicIds: [String]? {
        return getParam(PublicResourcesParams.publicIds.rawValue) as? [String]
    }
    
    // MARK: - Set Params
    
    /**
     Set an identifier that is used for publish resources.
     If not specified, a unique identifier is generated by Cloudinary.
     
     - parameter publicIds:       The identifiers.
     
     - returns:              A new instance of CLDPublishResourcesRequestParams.
     */
    @discardableResult
    open func setPublicIds(_ publicIds: [String]) -> CLDPublishResourcesRequestParams {
        setParam(PublicResourcesParams.publicIds.rawValue, value: publicIds)
        return self
    }
    
    /**
     Set a prefix that is used for for publish resources.
     
     - parameter prefix:     The prefix.
     
     - returns:              A new instance of CLDPublishResourcesRequestParams.
     */
    @discardableResult
    open func setPrefix(_ prefix: String) -> CLDPublishResourcesRequestParams {
        setParam(PublicResourcesParams.prefix.rawValue, value: prefix)
        return self
    }
    
    /**
     Set a tag that is used for for publish resources.
     
     - parameter tag:        The tag.
     
     - returns:              A new instance of CLDPublishResourcesRequestParams.
     */
    @discardableResult
    open func setTag(_ tag: String) -> CLDPublishResourcesRequestParams {
        setParam(PublicResourcesParams.tag.rawValue, value: tag)
        return self
    }

    // MARK: Private
    
    fileprivate enum PublicResourcesParams: String {
        case publicIds =            "public_ids"
        case tag =                  "tag"
        case prefix =               "prefix"
        case toType =               "to_type"
        case accessMode =           "access_mode"
    }
}
