# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoAlbum' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoAlbum
  pod 'Cloudinary', path: '../..'
  target 'PhotoAlbumTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
