name: iOS starter workflow

on:
  push:
    branches: [ test/github_actions ]
  pull_request:
    branches: [ test/github_actions ]

jobs:
  test:
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=12.2,name=iPhone X']
    steps:
        - uses: actions/checkout@v2
        - name: Create test Cloud
          run: |
             export CLOUDINARY_URL=$(bash tools/get_test_cloud.sh);
             echo cloud_name: "$(echo $CLOUDINARY_URL | cut -d'@' -f2)"
        - name: Install Dependencies
          run: |
            cd Example
            pod install
          shell: bash
        - name: Build and test
          run: |
            cd Example
             xcodebuild clean test -project Cloudinary.xcworkspace -scheme travis_public_scheme -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
          env:
            destination: ${{ matrix.destination }}
