name: Cloudinary iOS Tests

on:
  push:
    branches: [ test/github_actions ]
  pull_request:
    branches: [ test/github_actions ]

jobs:
  test:
    runs-on: macOS-latest
    steps:
        - uses: actions/checkout@v2
        - name: Create test Cloud
          run: |
            echo "CLOUDINARY_URL=$(bash tools/get_test_cloud.sh)" >> $GITHUB_ENV
        - name: Install Dependencies
          run: |
            cd Example
            pod install --repo-update
          shell: bash
        - name: Select Xcode version
          run: sudo xcode-select -s '/Applications/Xcode_12.1.app/Contents/Developer'
        - name: Build and test for iOS 15.0
          run: |
            cd Example
             xcodebuild clean test -workspace Cloudinary.xcworkspace -scheme travis_public_scheme -destination 'platform=iOS Simulator,OS=10.3.1,name=iPhone 8' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty
